NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

[7c48b4792587:28090] PMIX ERROR: PMIX_ERR_FILE_OPEN_FAILURE in file pmix_shmem.c at line 91
[7c48b4792587:28090] PMIX ERROR: PMIX_ERR_FILE_OPEN_FAILURE in file gds_shmem2.c at line 1056
[7c48b4792587:28090] PMIX ERROR: PMIX_ERR_FILE_OPEN_FAILURE in file gds_shmem2.c at line 1129
[7c48b4792587:28090] PMIX ERROR: PMIX_ERR_FILE_OPEN_FAILURE in file gds_shmem2.c at line 2519
[7c48b4792587:28090] PMIX ERROR: PMIX_ERR_FILE_OPEN_FAILURE in file gds_shmem2.c at line 2551
[7c48b4792587:28090] PMIX ERROR: PMIX_ERR_FILE_OPEN_FAILURE in file gds_shmem2.c at line 2576
[7c48b4792587:28090] PMIX ERROR: PMIX_ERR_UNPACK_FAILURE in file gds_shmem2.c at line 2578
[7c48b4792587:28090] *** Process received signal ***
[7c48b4792587:28090] Signal: Segmentation fault (11)
[7c48b4792587:28090] Signal code: Address not mapped (1)
[7c48b4792587:28090] Failing at address: 0x60
[7c48b4792587:28090] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x14420)[0x7f11f3b70420]
[7c48b4792587:28090] [ 1] /usr/local/pmix/lib/libpmix.so.2(pmix_gds_shmem2_fetch+0xa4)[0x7f11e3adcc94]
[7c48b4792587:28090] [ 2] /usr/local/pmix/lib/libpmix.so.2(pmix_hwloc_setup_topology+0x935)[0x7f11e39aa605]
[7c48b4792587:28090] [ 3] /usr/local/pmix/lib/libpmix.so.2(PMIx_Init+0x127a)[0x7f11e39b33ea]
[7c48b4792587:28090] [ 4] /usr/local/ompi/lib/libmpi.so.0(ompi_rte_init+0xf04)[0x7f11e3de55a4]
[7c48b4792587:28090] [ 5] /usr/local/ompi/lib/libmpi.so.0(+0xa19fa)[0x7f11e3dee9fa]
[7c48b4792587:28090] [ 6] /usr/local/ompi/lib/libmpi.so.0(ompi_mpi_instance_init+0x65)[0x7f11e3def775]
[7c48b4792587:28090] [ 7] /usr/local/ompi/lib/libmpi.so.0(ompi_mpi_init+0x83)[0x7f11e3de1803]
[7c48b4792587:28090] [ 8] /usr/local/ompi/lib/libmpi.so.0(PMPI_Init_thread+0x99)[0x7f11e3e19209]
[7c48b4792587:28090] [ 9] /home/mpiuser/.local/lib/python3.8/site-packages/mpi4py/MPI.cpython-38-x86_64-linux-gnu.so(+0x33cdf)[0x7f11e410ccdf]
[7c48b4792587:28090] [10] /opt/miniconda/envs/netpyne_env/lib/libpython3.8.so(PyModule_ExecDef+0x7a)[0x7f11f371965a]
[7c48b4792587:28090] [11] /opt/miniconda/envs/netpyne_env/lib/libpython3.8.so(+0x1995b6)[0x7f11f37195b6]
[7c48b4792587:28090] [12] /opt/miniconda/envs/netpyne_env/lib/libpython3.8.so(+0x1266be)[0x7f11f36a66be]
[7c48b4792587:28090] [13] /opt/miniconda/envs/netpyne_env/lib/libpython3.8.so(PyVectorcall_Call+0x71)[0x7f11f36b0721]
[7c48b4792587:28090] [14] /opt/miniconda/envs/netpyne_env/lib/libpython3.8.so(_PyEval_EvalFrameDefault+0x59af)[0x7f11f369f2ff]
[7c48b4792587:28090] [15] /opt/miniconda/envs/netpyne_env/lib/libpython3.8.so(_PyEval_EvalCodeWithName+0x2e2)[0x7f11f3698b32]
[7c48b4792587:28090] [16] /opt/miniconda/envs/netpyne_env/lib/libpython3.8.so(_PyFunction_Vectorcall+0x19d)[0x7f11f36a71cd]
[7c48b4792587:28090] [17] /opt/miniconda/envs/netpyne_env/lib/libpython3.8.so(_PyEval_EvalFrameDefault+0x4b7c)[0x7f11f369e4cc]
[7c48b4792587:28090] [18] /opt/miniconda/envs/netpyne_env/lib/libpython3.8.so(_PyFunction_Vectorcall+0x103)[0x7f11f36a7133]
[7c48b4792587:28090] [19] /opt/miniconda/envs/netpyne_env/lib/libpython3.8.so(_PyEval_EvalFrameDefault+0x6ae)[0x7f11f3699ffe]
[7c48b4792587:28090] [20] /opt/miniconda/envs/netpyne_env/lib/libpython3.8.so(_PyFunction_Vectorcall+0x103)[0x7f11f36a7133]
[7c48b4792587:28090] [21] /opt/miniconda/envs/netpyne_env/lib/libpython3.8.so(_PyEval_EvalFrameDefault+0x3b3)[0x7f11f3699d03]
[7c48b4792587:28090] [22] /opt/miniconda/envs/netpyne_env/lib/libpython3.8.so(_PyFunction_Vectorcall+0x103)[0x7f11f36a7133]
[7c48b4792587:28090] [23] /opt/miniconda/envs/netpyne_env/lib/libpython3.8.so(_PyEval_EvalFrameDefault+0x3b3)[0x7f11f3699d03]
[7c48b4792587:28090] [24] /opt/miniconda/envs/netpyne_env/lib/libpython3.8.so(_PyFunction_Vectorcall+0x103)[0x7f11f36a7133]
[7c48b4792587:28090] [25] /opt/miniconda/envs/netpyne_env/lib/libpython3.8.so(+0x12694b)[0x7f11f36a694b]
[7c48b4792587:28090] [26] /opt/miniconda/envs/netpyne_env/lib/libpython3.8.so(_PyObject_CallMethodIdObjArgs+0xf7)[0x7f11f36b1797]
[7c48b4792587:28090] [27] /opt/miniconda/envs/netpyne_env/lib/libpython3.8.so(PyImport_ImportModuleLevelObject+0x587)[0x7f11f36b1557]
[7c48b4792587:28090] [28] /opt/miniconda/envs/netpyne_env/lib/libpython3.8.so(+0x139afa)[0x7f11f36b9afa]
[7c48b4792587:28090] [29] /opt/miniconda/envs/netpyne_env/lib/libpython3.8.so(PyCFunction_Call+0x63)[0x7f11f36b05a3]
[7c48b4792587:28090] *** End of error message ***
